-- migration_60: App icon badge for unread chat messages
--
-- No new webhook needed — send-push already handles messages INSERT and sends
-- push notifications to conversation members. The badge feature is purely
-- client-side changes in src/App.jsx and src/sw.js.
--
-- If a webhook named on_chat_message_insert was created in the Supabase dashboard
-- pointing to send-chat-message-push, DELETE IT — it duplicates send-push and
-- causes two push events per message (two sounds/vibrations).
--
-- How the badge works:
-- - App open: App.jsx useEffect syncs unreadChatCount → navigator.setAppBadge(count)
--   Clears on /chat navigation.
-- - App closed/backgrounded: sw.js push handler calls navigator.setAppBadge(1)
--   alongside showNotification(). Clears on notification tap.
-- - Foreground suppression: if the user already has the target page visible,
--   both the notification popup and badge are skipped.
--
-- send-chat-message-push was deployed but should not have an active webhook.
-- It is superseded by the existing send-push function.
